name:  CI/CD

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      -  master

  pull_request:
    branches:
      - master

jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: test
        run: npm run test

      # should save this keys in github, settings of the project, secrets :
      # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
      - name: aws deploy
        run: BUILD_DIRECTORY=build BUCKET_NAME=ifonixapp AWS_ACCESS_KEY_ID=${{ AKIAZX2HF54Z5JBYI75E }} AWS_SECRET_ACCESS_KEY=${{ 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 }} npm run deploy-aws
