name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build

      # should save this keys in github, settings of the project, secrets :
      # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
      # - name: aws deploy
      #   run: BUILD_DIRECTORY=build BUCKET_NAME=ifonixapp AWS_ACCESS_KEY_ID=${{AKIAZX2HF54Z5JBYI75E}} AWS_SECRET_ACCESS_KEY=${{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}} npm run deploy-aws
      - name: aws deploy
        env:
          AWS_ACCESS_KEY_ID: ${{AKIAZX2HF54Z5JBYI75E}}
          AWS_SECRET_ACCESS_KEY: ${{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}}
        run: BUILD_DIRECTORY=build BUCKET_NAME=ifonixapp npm run deploy-aws
