name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  primary:
    runs-on: ubuntu 20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build

      # should save these keys in GitHub, settings of the project, secrets:
      # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
      - name: aws deploy
        env:
          BUILD_DIRECTORY: build
          BUCKET_NAME: ifonixapp
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:  npm run deploy-aws
